kind: ZarfPackageConfig
metadata:
  name: rocketchat-traefik
  description: Traefik loadbalancer
  version: 3.5.0-z1

components:
  - name: traefik
    required: true
    charts:
      - name: traefik
        version: v37.0.0
        namespace: traefik
        url: https://helm.traefik.io/traefik
        releaseName: traefik
        valuesFiles:
          - traefik-values.yaml

    healthChecks:
      - name: traefik
        namespace: traefik
        apiVersion: apps/v1
        kind: Deployment

    images:
      - docker.io/traefik:v3.5.0

variables:
  - name: LOADBALANCER_SERVICE_TYPE
    description: "The Kubernetes Service type for Traefik"
    default: "LoadBalancer"
  - name: LOADBALANCER_SERVICE_ANNOTATIONS
    description: "Cloud-specific annotations for Traefik"
    default: "{}" # Default to empty for K3s/On-prem, or
    # example: zarf package deploy --set LOADBALANCER_SERVICE_ANNOTATIONS='{service.beta.kubernetes.io/aws-load-balancer-type: "nlb"}'



