apiVersion: v1
kind: Secret
metadata:
  name: airlock-workspaces
  namespace: mongodb
type: Opaque
stringData:
  connectionString: "mongodb://workspaces-admin:###ZARF_VAR_DATABASE_ADMIN_PASSWORD###@workspaces-0.workspaces-svc.mongodb.svc.cluster.local:27017,workspaces-1.workspaces-svc.mongodb.svc.cluster.local:27017,workspaces-2.workspaces-svc.mongodb.svc.cluster.local:27017/?replicaSet=workspaces&ssl=false"
