apiVersion: v1
kind: Secret
metadata:
  name: metrics-endpoint-password
  namespace: mongodb
type: Opaque
stringData:
  password: ###ZARF_VAR_DATABASE_METRICS_PASSWORD_INTERNAL###
  username: prometheus-username
