apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rocketchat-pod-monitor
  namespace: ###ZARF_VAR_WORKSPACE_NAME###-workspace
spec:
  podMetricsEndpoints:
    - port: rc-metrics
      interval: "30s"
    - port: ms-metrics
      interval: "30s"
  selector:
    matchLabels:
      x-launchpad-monitoring: active
